# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots

# NB: don't set `language: haskell` here

# The following enables several GHC versions to be tested; often it's
# enough to test only against the last release in a major GHC
# version. Feel free to omit lines listings versions you don't
# need/want testing for.
env:
# - GHCVER=7.4.1
# - GHCVER=7.4.2
 - GHCVER=7.6.1
 - GHCVER=7.6.2
 - GHCVER=7.6.3
 - GHCVER=7.8.1
 - GHCVER=7.8.3
 - GHCVER=7.8.4
 - GHCVER=head  # see section about GHC HEAD snapshots

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.18 update
# This is a hack to make Travis happy because it doesn't install happy/alex by default
 - cabal-1.18 install happy alex
# And now we install the main packages:
 - PKGS="./atomic-primops ./atomic-primops-foreign ./abstract-deque/ ./abstract-deque-tests/ ./lockfree-queue/ ./chaselev-deque/ ./mega-deque"
 - cabal-1.18 install $PKGS
# Now enable benchmarks and tests and add the extra dependencies:
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks $PKGS

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - (cd ./atomic-primops/testing; cabal-1.18 test --show-details=always)
 - (cd ./atomic-primops-foreign; cabal-1.18 configure; cabal-1.18 test --show-details=always)
 - (cd ./abstract-deque;         cabal-1.18 configure; cabal-1.18 test --show-details=always)
 - (cd ./lockfree-queue//;       cabal-1.18 configure; cabal-1.18 test --show-details=always)
 - (cd ./chaselev-deque/;        cabal-1.18 configure; cabal-1.18 test --show-details=always)
 - (cd ./mega-deque/;            cabal-1.18 configure; cabal-1.18 test --show-details=always)
